version: '3.8'
services:
  postgres:
    container_name: auth_pg
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5433:80
volumes:
  pg_volume:
